INSERT INTO JOB(ID, DESCRIPTION, EMPLOYER, TITLE) VALUES(100,'AGRONOMO ESPECIALIZADO','PR SUPPLIES', 'AGRONOMO');
INSERT INTO JOB(ID, DESCRIPTION, EMPLOYER, TITLE) VALUES(200,'INGENIERO CIVIL','AIREKO CONSTRUCTION', 'INGENIERO');
INSERT INTO JOB(ID, DESCRIPTION, EMPLOYER, TITLE) VALUES(300,'PROSTITUTA ESPECIALIZADA SEXO ORAL','PR SUPPLIES', 'PROSTITUTA');